name: CI

on:
  pull_request:
    paths-ignore:
      - "docs/**"
      - "**.md"
      - ".*"
  push:
    branches:
      - main
      - "release-*"

concurrency:
  group: ci-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  flink-omt:
    uses: ./.github/workflows/test.yml
    with:
      module: flink-omt
