name: CI

on:
  pull_request:
    paths-ignore:
      - "docs/**"
      - "**.md"
      - ".*"
  push:
    branches:
      - main
      - "release-*"

concurrency:
  group: ci-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test_starrocks:
    uses: ./.github/workflows/test_starrocks.yml
    with:
      module: flink-omt

  test_doris:
    uses: ./.github/workflows/test_doris.yml
    with:
      module: flink-omt

  test_ck:
    uses: ./.github/workflows/test_clickhouse.yml
    with:
      module: flink-omt
